name: Build and Test

on:
  push

jobs:
    build:
        name: Build and Test Qt${{ matrix.qt_ver }}
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
              qt_ver: [5.15.0]
        steps:
          - name: Install Qt
            uses: jurplel/install-qt-action@v2
            with:
              version: ${{ matrix.qt_ver }}
              modules: 'multimedia multimediawidgets'
          - name: Git Checkout
            uses: actions/checkout@v2
          - name: Create Build Directory
            shell: pwsh
            run: |
              mkdir build
              cd build
          - name: Build
            shell: pwsh
            run: |
              cd build
              qmake -makefile ../
              make
